[workspace]
members = ["client", "server", "shared"]

[workspace.dependencies]

glam = { version = "0.22.0", features = ["rand"] }
rand = "0.8.5"
itertools = "0.10.5"


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
